# Generated by Django 5.2.8 on 2026-05-21 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ministry_hospital_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgeryreport',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='surgeryreport',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='surgeryreport',
            name='oxygen_saturation',
        ),
        migrations.RemoveField(
            model_name='surgeryreport',
            name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='surgeryreport',
            name='respiratory_rate',
        ),
        migrations.RemoveField(
            model_name='surgeryreport',
            name='temperature_c',
        ),
        migrations.AlterField(
            model_name='mrireport',
            name='after_scan',
            field=models.FileField(blank=True, null=True, upload_to='mri/after/'),
        ),
        migrations.AlterField(
            model_name='mrireport',
            name='before_scan',
            field=models.FileField(blank=True, null=True, upload_to='mri/before/'),
        ),
        migrations.AlterField(
            model_name='surgeryreport',
            name='report_image',
            field=models.FileField(blank=True, null=True, upload_to='surgery_reports/images/'),
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
