# Generated by Django 5.2.8 on 2026-05-21 22:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_surgeryreport_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryreport',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
