# Generated by Django 5.2.8 on 2026-05-21 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_surgeryreport_recorded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.hospital'),
        ),
    ]
